# pyproject.toml
[project]
name = "comfyui-usefulstuffnodes"
description = "Utility ComfyUI custom nodes that add some extra features for your workflows (random int for cli runs, unix timestamp, etc)."
version = "0.0.1"
license = { text = "MIT" }
dependencies  = []

[project.urls]
Repository = "https://github.com/ArtemKo7v/ComfyUI-UsefulStuffNodes"

[tool.comfy]
PublisherId = "artemko7v"
DisplayName = "ComfyUI Useful Stuff Nodes"
